version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: location-share-redis
    ports:
      - "6384:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    environment:
      - REDIS_PASSWORD=
    restart: unless-stopped

  app:
    build: .
    container_name: location-share-server
    ports:
      - "8083:8083"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=
      - REDIS_DB=0
      - NODE_ENV=production
    depends_on:
      - redis
    restart: unless-stopped

volumes:
  redis_data:
